DEFINE
	VAR __DS0FilterTable = 
		FILTER(KEEPFILTERS(VALUES('window size'[window size])), 'window size'[window size] = 86)

	VAR __DS0Core = 
		SUMMARIZECOLUMNS(
			ROLLUPADDISSUBTOTAL('Calendar Lookup'[Weekend], "IsGrandTotalRowTotal"),
			__DS0FilterTable,
			"Total_Orders", 'Measure Table(DAX)'[Total Orders],
			"v__of_all_orders", 'Measure Table(DAX)'[% of all orders]
		)

	VAR __DS0PrimaryWindowed = 
		TOPN(502, __DS0Core, [IsGrandTotalRowTotal], 0, 'Calendar Lookup'[Weekend], 1)

EVALUATE
	__DS0PrimaryWindowed

ORDER BY
	[IsGrandTotalRowTotal] DESC, 'Calendar Lookup'[Weekend]