table 'Product Categories Lookup'
	lineageTag: f43ef610-7b63-45a3-a968-81b0bf8eaa69

	column ProductCategoryKey
		dataType: int64
		isKey
		formatString: 0
		lineageTag: 9b9d8b9a-bb41-4dad-acdb-a8715fe515c2
		summarizeBy: none
		sourceColumn: ProductCategoryKey

		annotation SummarizationSetBy = Automatic

	column CategoryName
		dataType: string
		lineageTag: ff68a1b1-8fbf-4b79-a301-6b5d49b2a2a5
		summarizeBy: none
		sourceColumn: CategoryName

		annotation SummarizationSetBy = Automatic

	partition 'Product Categories Lookup' = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("D:\POWER BI\AdventureWorks+Raw+Data\AdventureWorks Raw Data\Adventures\AdventureWorks Product Categories Lookup.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ProductCategoryKey", Int64.Type}, {"CategoryName", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

